//stock constants
export const INSERTDEPARTMENT="INSERTDEPARTMENT";
export const GETALLDEPARTMENTS="GETALLDEPARTMENTS"; 
export const GETDEPARTMENT="GETDEPARTMENT";
export const DELETEDEPARTMENT="DELETEDEPARTMENT";
export const UPDATEDEPARTMENT="UPDATEDEPARTMENT";

